[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
said = "Da5VT4SJerSuwnA1byc8W4uD3wYhwD1c9qKFLtN3sCPR"

[programs.devnet]
said = "SAiD111111111111111111111111111111111111111"

[programs.mainnet]
said = "Da5VT4SJerSuwnA1byc8W4uD3wYhwD1c9qKFLtN3sCPR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
